# /apps/stack/docker-compose.yml
services:
  memoservice:
    image: ghcr.io/shaojunliu/memoservice:latest   # ← 镜像来源：GHCR
    container_name: memoservice
    env_file:
      - /apps/stack/.env                           # ← 你的环境变量文件（在服务器）
    ports:
      - "${SERVER_PORT:-8080}:8080"                # ← 外部端口：环境变量优先，默认8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8080/healthz"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/memo?currentSchema=public
      DB_DRIVER: org.postgresql.Driver
      DB_DDL_AUTO: validate

  agent:
    image: ghcr.io/shaojunliu/agent:latest
    container_name: agent
    env_file:
      - /apps/stack/.env
    ports:
      - "${AGENT_PORT:-8001}:8001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8001/healthz"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }
    # networks:
    #   - prod
# networks:
#   prod:
#     driver: bridge
