# /apps/stack/docker-compose.yml
networks:
  appnet:
    driver: bridge

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: memo
      POSTGRES_USER: HPLB
      POSTGRES_PASSWORD: 20250817
    ports:
      - "5432:5432"
    networks:
      - appnet
  memoservice:
    image: ghcr.io/shaojunliu/memoservice:latest   # ← 镜像来源：GHCR
    container_name: memoservice
    env_file:
      - /apps/stack/.env                           # ← 你的环境变量文件（在服务器）
    ports:
      - "${SERVER_PORT:-8080}:8080"                # ← 外部端口：环境变量优先，默认8080
    networks:
      - appnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'exec 3<>/dev/tcp/127.0.0.1/8080' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/memo?currentSchema=public
      DB_DRIVER: org.postgresql.Driver
      DB_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      DB_DDL_AUTO: validate
      DB_USER: HPLB
      DB_PASS: 20250817
      APP_AGENT_BASE_URL: http://agent:8001

  agent:
    image: ghcr.io/shaojunliu/agent:latest
    container_name: agent
    env_file:
      - /apps/stack/.env
    ports:
      - "${AGENT_PORT:-8001}:8001"
    networks:
      - appnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8001/healthz"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    environment:
      DASHSCOPE_API_KEY: ${DASHSCOPE_API_KEY}
      AGENT_API_KEY: ${AGENT_API_KEY}
      OPEN_API_KEY: ${OPEN_API_KEY}
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }
