server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true   # 提供 /actuator/health/readiness 等
spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:wx;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USER:HPLB}
    password: ${DB_PASS:20250817}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}   # 测试用 update，生产改 validate
    properties:
      hibernate.dialect: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console   # 控制台访问路径，默认也是这个http://localhost:8080/h2-console
  security:
    user:
      name: memo
      password: HPLB_20250817
jwt:
  secret: B7v5oaYr_wEHlBKz9SrVMCYHea2884j7RrNG_qXdr6lNbkNswd5RCjIAxSUvqcZ_iSm_d8FAGW8sRsN7-mDs8g==    # 至少32字节
  ttl-seconds: 604800    # 7天

# 微信/登录配置
  # •	appid：在微信小程序后台（mp.weixin.qq.com → 开发 → 开发管理 → 开发设置）里能找到。
  #  •	secret：同样在后台 → 开发设置里有“AppSecret”，需要点击生成。
wx:
  appid: wx24a59aa9e1797a8d
  secret: 06ab9e3e03d2448385e6bcac5d09746d
  mock: false

agent:
  url: ${APP_AGENT_BASE_URL:ws://agent:8001/ws/chat}
  api-key: HPLB_20250817
  connect-timeout-ms: 2000
  read-timeout-ms: 8000